server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: systemd-journal
    journal:
      max_age: 12h
      labels:
        job: journal
        host: prom-graf
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: '(sshd|nginx|docker|fail2ban|systemd).*'
        target_label: 'unit'
